### ISSUE TITLE
Add vars in scenario

### ISSUE THREAD

**Issue by EliasBoulharts** [HewlettPackard/monkeyble#28]
It would be useful to assign variables to the scenarios. We could have a common set of variables for all scenarios, and change one or more variables for each scenario.

**Comment by Sispheor** [comment]
Already possible.
As an example here I use common vars and sone specific vars for the targe scenario.

```yaml
  - playbook: "playbooks/openshift_dedicated_cluster/vmware_iaas_lr1/create_cluster.yml"
    inventory: "/runner/inventory/squest/inventory.yml"
    extra_vars:
      - "playbooks/openshift_dedicated_cluster/vmware_iaas_lr1/testing_vars/create_cluster_common.vars.yml"
      - "playbooks/openshift_dedicated_cluster/vmware_iaas_lr1/testing_vars/create_cluster.monkeyble.vars.yml"
      - "playbooks/openshift_dedicated_cluster/vmware_iaas_lr1/testing_vars/create_cluster_standard.vars.yml"
    scenarios:
      - validate_can_create_ocp_in_vmware_standard
  - playbook: "playbooks/openshift_dedicated_cluster/vmware_iaas_lr1/create_cluster.yml"
    inventory: "/runner/inventory/squest/inventory.yml"
    extra_vars:
      - "playbooks/openshift_dedicated_cluster/vmware_iaas_lr1/testing_vars/create_cluster_common.vars.yml"
      - "playbooks/openshift_dedicated_cluster/vmware_iaas_lr1/testing_vars/create_cluster.monkeyble.vars.yml"
      - "playbooks/openshift_dedicated_cluster/vmware_iaas_lr1/testing_vars/create_cluster_az.vars.yml"
    scenarios:
      - validate_can_create_ocp_in_vmware_with_az
```
